# Travis CI scripts (python, php)
# Python script (other languages are at the end.)
language: minimal # debugging setup
# language: python
# python:
#   # - "2.7"
#   - "3.7"

# command to install dependencies
install:
  # Default ...
  # - pip install -r requirements.txt
  # - pip install .
  # Specific ...
  - pip install -e .
  # Limit setuptools as some newer versions have Issues(tm). This needs doing
  # as its own step; trying to do it via requirements.txt isn't always
  # sufficient.
  - pip install "setuptools<34"
  # Dev requirements
  # TODO: follow invoke and split it up a bit so we're not pulling down
  # conflicting or unused-by-travis deps?
  - pip install -r dev-requirements.txt
# command to run tests
script:
#   - pytest
  # Fail if any of these files have warnings
#   - shellcheck myscripts/*.sh
after_success:
  # Upload coverage data to codecov
  - codecov
notifications:
  email: skeptycal@gmail.com
